# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSONMapping' do
  use_frameworks!
#  pod 'HandyJSON'
#  pod 'SwiftyJSON'

  # Pods for JSONMapping

end
